# Generated by Django 3.2 on 2021-04-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granjas', '0003_historicalavicola_historicalgalpon_historicalgranja'),
    ]

    operations = [
        migrations.AddField(
            model_name='granja',
            name='capacidad',
            field=models.CharField(default='0', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalgranja',
            name='capacidad',
            field=models.CharField(default='0', max_length=50),
            preserve_default=False,
        ),
    ]
